apiVersion: v2
appVersion: "1.0"
description: A Helm chart for et-pet admin application
name: et-pet-admin
home: https://github.com/hmcts/et-pet-admin
version: 0.0.16
dependencies:
  - name: base
    version: 1.4.1
    repository: 'oci://hmctspublic.azurecr.io/helm'
